package gob.conafor.ini.vie;

import java.io.File;
import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
//import org.apache.commons.io.FileUtils;


/**
 *
 * @author ecalderon
 */
public class FrmBaseDatos extends javax.swing.JInternalFrame {
    private File destDir;
    private File srcFile;

   
    public FrmBaseDatos() {
        initComponents();
        fcBaseDatos.setDialogTitle("Generar base de datos");
        fcBaseDatos.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fcBaseDatos.setAcceptAllFileFilterUsed(false);
        
        Path currentPath = Paths.get("");
        String path = currentPath.toAbsolutePath().toString();
        String pathBaseDatos = path + "/src/db/MuestreoINF_2015.db";
        this.srcFile = new File(pathBaseDatos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fcBaseDatos = new javax.swing.JFileChooser();

        fcBaseDatos.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        fcBaseDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fcBaseDatosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fcBaseDatos, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(fcBaseDatos, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fcBaseDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fcBaseDatosActionPerformed
        fcBaseDatos = (JFileChooser) evt.getSource();
        String command = evt.getActionCommand();
        if (command.equals(JFileChooser.APPROVE_OPTION)) {
            
             //this.destDir = fcBaseDatos.getCurrentDirectory();
            JOptionPane.showMessageDialog(this, "Ruta: " + fcBaseDatos.getCurrentDirectory());
            // File archivoSeleccionado = fcBaseDatos.getSelectedFile();
            /*
            try {
                FileUtils.copyFile(srcFile, destDir);
            } catch (Exception e) {
               JOptionPane.showMessageDialog(null,
                    "Error, No se pudo generar el archivo " + e.getClass().getName() + ": " + e.getMessage());
            }*/
        } else if (command.equals(JFileChooser.CANCEL_SELECTION)) {
            this.hide();
        }
    }//GEN-LAST:event_fcBaseDatosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser fcBaseDatos;
    // End of variables declaration//GEN-END:variables
}
