package gob.conafor.ini.vie;

import gob.conafor.sitio.mod.CDSitio;
import gob.conafor.sitio.mod.CESitio;
import gob.conafor.upm.mod.CDUpm;
import gob.conafor.upm.vie.UPMForms;
import gob.conafor.utils.FuncionesComunes;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

public class FrmModulos extends javax.swing.JDialog {

    protected static final  int RET_CANCEL = 0;
    protected static final int RET_OK = 1;
    protected boolean iniciar = false;
    private CDUpm upm = new CDUpm();
    private CDSitio cdSitio = new CDSitio();
    private FuncionesComunes combo = new FuncionesComunes();
    private CDUpm cdUpm = new CDUpm();
    private Integer secuenciaID;
    private Integer sitioID;
    
    public FrmModulos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        fillCmbUPM();
        this.setLocationRelativeTo(Main.main);
        //Cerrar ventana al presionar cancelar
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }
    
    private void abilitarBotonInicio() {
        if (cmbUPM.getSelectedItem() != null && cmbSitios.getSelectedItem() != null) {
            btnIniciar.setEnabled(true);
        } else {
            btnIniciar.setEnabled(false);
        }
    }
    
    private void fillCmbUPM(){
        List<Integer> listUPM = new ArrayList<>();
        listUPM = cdSitio.getUPMS();
        if(listUPM != null){
            int size = listUPM.size();
            for(int i = 0; i < size; i++){
                cmbUPM.addItem(listUPM.get(i));
            }
        }
    }
    
    private void fillCmbSitios(int upmID){
       List<Integer> listSitios = new ArrayList<>();
       //listSitios = cdSitio.getSitiosAccesibles(upmID);
       if(listSitios != null){
           int size = listSitios.size();
           for(int i = 0; i < size; i++){
               cmbSitios.addItem(listSitios.get(i));
           }
       }
    }
    
    private void setSecuencia(int upmID){
        secuenciaID = this.cdUpm.getSecuenciaID(upmID);
    }
    private Integer getSecuencia(){
        return secuenciaID;
    }
    private void setSitioID(Integer upmID, Integer sitio){
        this.sitioID = cdSitio.getSitioID(upmID, sitio);
    }
    private Integer getSitioID(){
       return  this.sitioID;
    }
    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
   /* public int getReturnStatus() {
        return returnStatus;
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIniciar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbUPM = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cmbSitios = new javax.swing.JComboBox();
        btnCancelar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();

        setTitle("Captura de formatos");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        btnIniciar.setMnemonic('i');
        btnIniciar.setText("Iniciar");
        btnIniciar.setToolTipText("Iniciar la captura de una UPM");
        btnIniciar.setEnabled(false);
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder()));

        jLabel1.setText("UPM:");

        cmbUPM.setToolTipText("Unidad primaria de muestreo");
        cmbUPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbUPMActionPerformed(evt);
            }
        });
        cmbUPM.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cmbUPMPropertyChange(evt);
            }
        });

        jLabel2.setText("Sitio:");

        cmbSitios.setToolTipText("Tipo de UPM encontrado en campo");
        cmbSitios.setEnabled(false);
        cmbSitios.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cmbSitiosPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbSitios, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbUPM, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbUPM, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbSitios, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        btnCancelar.setMnemonic('c');
        btnCancelar.setText("Cancelar");
        btnCancelar.setToolTipText("Omitir la captura de una UPM");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Iniciar captura de formatos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(btnCancelar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblTitulo)
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIniciar)
                    .addComponent(btnCancelar))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        getRootPane().setDefaultButton(btnIniciar);

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        doClose(RET_OK);
        iniciar = true;
        Integer upmID = (Integer) cmbUPM.getSelectedItem();
        Integer sitio = (Integer) cmbSitios.getSelectedItem();
        setSitioID(upmID, sitio);
        
        CESitio ceSitio = new CESitio();
        setSecuencia(upmID);
        Integer secuenciaID = getSecuencia();
        
        ceSitio.setUpmID(upmID);
        ceSitio.setSitio(sitio);
        ceSitio.setSecuencia(secuenciaID);
        ceSitio.setSitioID(getSitioID());
        
        if (secuenciaID != null) {
            switch (secuenciaID) {
                case 1: //Módulo A
                    UPMForms.sotoBosque.setDatosIniciales(ceSitio); 
                    UPMForms.sotoBosque.setVisible(true);
                    break;
                case 2: //Módulos A y C
                    UPMForms.sotoBosque.setDatosIniciales(ceSitio); 
                    UPMForms.sotoBosque.setVisible(true);
                    break;
                case 3: //Modulos A, C, E y G
                    UPMForms.claveVegetacion.setDatosIniciales(ceSitio);
                    UPMForms.claveVegetacion.setVisible(true);
                    break;
                case 4: //Modulos A y E
                    UPMForms.sotoBosque.setDatosIniciales(ceSitio);
                    UPMForms.sotoBosque.setVisible(true);
                    break;
                case 5: //Modulos A, C, D y F
                    UPMForms.sotoBosque.setDatosIniciales(ceSitio);
                    UPMForms.sotoBosque.setVisible(true);
                    break;
                case 6://Modulos A, C y D
                    UPMForms.sotoBosque.setDatosIniciales(ceSitio);
                    UPMForms.sotoBosque.setVisible(true);
                    break;
                case 7://Modulos A, C, D y E
                    UPMForms.sotoBosque.setDatosIniciales(ceSitio);
                    UPMForms.sotoBosque.setVisible(true);
                    break;
                case 8://Modulos A, C, D, E y F
                    UPMForms.sotoBosque.setDatosIniciales(ceSitio);
                    UPMForms.sotoBosque.setVisible(true);
                    break;
                case 9://Modulos A, C y E
                    UPMForms.sotoBosque.setDatosIniciales(ceSitio);
                    UPMForms.sotoBosque.setVisible(true);
                    break;
                case 10://Modulos A, C, H
                    UPMForms.repoblado.setDatosIniciales(ceSitio);
                    UPMForms.repoblado.setVisible(true);
                    break;
                case 11://Modulos A y H
                    UPMForms.repoblado.setDatosIniciales(ceSitio);
                    UPMForms.repoblado.setVisible(true);
                    break;
                case 12://Modulos A, E y H
                    UPMForms.repoblado.setDatosIniciales(ceSitio);
                    UPMForms.repoblado.setVisible(true);
                    break;
                case 13://Modulos A, C, E y H
                    UPMForms.repoblado.setDatosIniciales(ceSitio);
                    UPMForms.repoblado.setVisible(true);
                    break;
                case 14://Modulos A, E y G
                    UPMForms.claveVegetacion.setDatosIniciales(ceSitio);
                    UPMForms.claveVegetacion.setVisible(true);
                    break;
                case 15://A y G
                    UPMForms.claveVegetacion.setDatosIniciales(ceSitio);
                    UPMForms.claveVegetacion.setVisible(true);
                    break;
            }
        }
    }//GEN-LAST:event_btnIniciarActionPerformed

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        //doClose(RET_CANCEL);
        this.dispose();
    }//GEN-LAST:event_closeDialog

    private void cmbUPMPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cmbUPMPropertyChange
       abilitarBotonInicio();
    }//GEN-LAST:event_cmbUPMPropertyChange

    private void cmbSitiosPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cmbSitiosPropertyChange
       abilitarBotonInicio();
    }//GEN-LAST:event_cmbSitiosPropertyChange

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
        iniciar = false;
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cmbUPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUPMActionPerformed
        Integer upmID = (Integer) cmbUPM.getSelectedItem();
        if (upmID != null) {
            cmbSitios.setEnabled(true);
            combo.reiniciarComboModel(cmbSitios);
            fillCmbSitios(upmID);
        } else {
            cmbSitios.setSelectedItem(null);
            cmbSitios.setEnabled(false);
            combo.reiniciarComboModel(cmbSitios);
        }
    }//GEN-LAST:event_cmbUPMActionPerformed
    
    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    /**
     * @param args the command line arguments
     */
  /*  public static void main(String args[]) {
        // Set the Nimbus look and feel 
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
     /*  try{
             
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            
        }catch (Exception e){
            
            e.printStackTrace();
            
        }*/
        //</editor-fold>

         //Create and display the dialog 
    /*    java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgTipoUPM dialog = new DlgTipoUPM(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnIniciar;
    protected javax.swing.JComboBox cmbSitios;
    protected javax.swing.JComboBox cmbUPM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;
}
