--
-- File generated with SQLiteStudio v3.1.1 on lun. may. 29 12:30:52 2017
--
-- Text encoding used: System
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: BRIGADA_Brigadistas
DROP TABLE IF EXISTS BRIGADA_Brigadistas;

CREATE TABLE BRIGADA_Brigadistas (
    BrigadistaID    INTEGER       PRIMARY KEY ASC AUTOINCREMENT,
    Nombre          VARCHAR (100),
    ApellidoPaterno VARCHAR (100),
    ApellidoMaterno VARCHAR (100),
    PuestoID        INT,
    Activo          INT,
    EmpresaID       INTEGER
);

INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (1, 'José Caín ', 'Calvillo', 'García', 1, 1, 1);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (2, 'José Ernesto', 'Hernández', 'Ramirez', 0, 1, 1);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (3, 'Román ', 'Castro', 'Ortíz', 0, 1, 1);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (4, 'Tomás ', 'Yescas ', 'de los Ángeles', 1, 1, 1);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (5, 'Francisco', 'Yescas ', 'de los Ángeles', 0, 1, 1);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (6, 'José ', 'Yescas ', 'de los Ángeles', 0, 1, 1);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (7, 'Carolina', 'Mendoza', 'Sánchez', 0, 1, 1);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (8, 'Javier ', 'Mendoza', 'Velasco', 0, 1, 1);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (9, 'Daniel', 'Trinidad', 'Hernández', 0, 1, 1);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (10, 'Jesús', 'Páramo', 'Águila', 1, 1, 1);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (11, 'Wilfrido ', 'Méndez', 'García', 0, 1, 1);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (12, 'Abigail ', 'Leandro', 'Martínez', 0, 1, 1);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (13, 'Eutropio', 'Sánchez', 'Sánchez', 1, 1, 1);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (14, 'Nallely', 'Pacheco', 'López', 0, 1, 1);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (15, 'Jenaro ', 'Reyes', 'Martínez', 0, 1, 1);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (16, 'Juan Gabriel', 'Baquedano', 'Peralta', 1, 1, 1);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (17, 'Renan', 'Baquedano', 'Peralta', 0, 1, 1);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (18, 'Prudencio', 'Tolentino', 'Dimas', 0, 1, 1);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (19, 'Angélica', 'Hernández', 'García', 1, 1, 1);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (20, 'Saúl', 'George', 'Miranda', 1, 1, 1);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (21, 'Salvador de Jesús', 'Urquilla', 'Climaco', 0, 1, 1);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (22, 'Ignacio', 'Martínez', 'Martínez', 1, 1, 1);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (23, 'Irma Graciela', 'Hernández', 'Vera', 0, 1, 1);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (24, 'Joaquín', 'García', 'Barrios', 0, 1, 1);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (25, 'José Luis', 'Flores', 'Nicanor', 1, 1, 1);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (26, 'Abraham ', 'Rojano', 'Álvarez', 0, 1, 1);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (27, 'Ulises', 'Rojano', 'Agustín', 0, 1, 1);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (28, 'Juan Carlos', 'Bautista', 'Martínez', 1, 1, 1);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (29, 'Víctor ', 'Eufrasio ', 'Juan', 0, 1, 1);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (30, 'Cesareo', 'Pérez', 'López', 0, 1, 1);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (31, 'David ', 'Bautista', 'Paez', 1, 1, 1);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (32, 'Martín Faustino', 'Pérez', 'Juárez', 0, 1, 1);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (33, 'Luz Adriana', 'Sánchez', 'Martínez', 0, 1, 1);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (34, 'Roman', 'Bacilio', 'López', 1, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (35, 'Jonathan', 'Ramírez', 'Arce', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (36, 'Mayte', 'Juárez', 'Reyes', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (37, 'Miguel Ángel', 'Becerra', 'Jiménez', 1, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (38, 'Emma Lilia', 'Hernández', 'Sánchez', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (39, 'Juan José', 'Barragán', 'Arias', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (40, 'José', 'Beristain', 'Ruiz', 1, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (41, 'Norma Lucia', 'Zepahua', 'Ixmatlahua', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (42, 'Gerardo', 'Vázquez', 'Popocatl', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (43, 'Oswaldo Fabián', 'Cruz', 'Hernández', 1, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (44, 'Josias Jehu', 'Soto', 'Rodríguez', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (45, 'Deysi', 'Benito', 'de la Cruz', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (46, 'Isai', 'Juárez', 'Vargas', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (47, 'Juan', 'García', 'Díaz', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (48, 'Luis Antonio', 'López', 'Cruz', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (49, 'Lizeth', 'Cervantes', 'Fuentes', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (50, 'Martín', 'García', 'García', 1, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (51, 'Erick Alonso', 'Antonio', 'Hernández', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (52, 'Eddy Raciel', 'Patrarca', 'Hernández', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (53, 'Felipe', 'González', 'Bautista', 1, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (54, 'Luis', 'Vázquez', 'Cruz', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (55, 'Jorge', 'Vázquez', 'Maya', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (56, 'Natalia', 'Pérez', 'García', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (57, 'Kevin Ulises', 'Jacobo', '', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (58, 'Dan', 'De Olarte', 'Torres', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (59, 'José Luís', 'Oltehua', 'Tzitzihua', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (60, 'Elias Daniel', 'Jimenez', 'Chavez', 1, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (61, 'Luis Eduardo', 'Camacho', 'Ortíz', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (62, 'Victoria', 'Vicente', 'Adan', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (63, 'Belen', 'Arango', 'Castillo', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (64, 'Cecilio', 'Jimenez', 'Romero', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (65, 'Erik', 'Jimenez', 'Casiano', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (66, 'Josue', 'Mendoza', 'Prisciliano', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (67, 'Esteban', 'Martínez', 'Mateo', 1, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (68, 'Juan Carlos', 'Nava', 'Vera', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (69, 'Carmina', 'Torres', 'Cruz', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (70, 'Luis Antonio', 'Cortes', 'Jaramillo', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (71, 'Estafany Guadalupe', 'Vazquez', 'Soria', 1, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (72, 'Melquiades', 'Muñoz', 'Chavez', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (73, 'Aldo Alan', 'Morales', 'Dominguez', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (74, 'Ángel', 'Antonio', 'Mendoza', 1, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (75, 'Jessica Aremi', 'Morales', 'Pérez', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (76, 'Francisco Walther', 'Peñate', 'Arcos', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (77, 'Rodolfo', 'Villa', 'Cano', 1, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (78, 'Alfredo', 'Pedro', 'Rosales', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (79, 'Leonor', 'Hernández', 'Hernández', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (80, 'German', 'Namigtle', 'Flores', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (81, 'Antonia', 'Rayon', 'Muñoz', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (82, 'Leonel Isai', 'Chavez', 'Hernández', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (83, 'Rafael', 'Hernández', 'Ortiz', 1, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (84, 'Jorge Abraham', 'Pérez', 'Pérez', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (85, 'Estrella', 'Marín', 'Mayahua', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (86, 'Juan de Jesus', 'Ramos', 'Olvera', 1, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (87, 'Felipe Agustin', 'Lara', 'Hernández', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (88, 'Raquel', 'Espinoza', 'López', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (89, 'Gabriel', 'Santander', 'Martinez', 1, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (90, 'Demesio', 'Macario', 'Cueyactle', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (91, 'Diana', 'Vera', 'Castillo', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (92, 'Christopher Ayocuar', 'Ventura', 'Alfaro', 1, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (93, 'Baruc Alexis', 'Navarrete', 'Mendez', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (94, 'Mirna Saraí', 'Flores', 'Cano', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (95, 'Jacobo', 'Carmona', 'Fernandez', 1, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (96, 'Cesar Adan', 'Ayala', 'Villalobos', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (97, 'Mateo', 'Bravo', 'Chuela', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (98, 'Saul', 'Garcia', 'Sanchez', 1, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (99, 'Aziel', 'Garcia', 'Perez', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (100, 'Jose Guadalupe', 'Garcia', 'Perez', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (101, 'Aida', 'Paz', 'Maldonado', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (102, 'Angel Antonio', 'Acevedo', 'Franco', 1, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (103, 'Arturo', 'Hernandez', 'Tapia', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (104, 'Javier Pazcual', 'Garabito', 'Mendez', 1, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (105, 'Laura Adriana', 'Escobedo', 'Baez', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (106, 'Marcos Miguel', 'Garabito', 'Mendez', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (107, 'Baltazar', 'Prieto', 'Morales', 1, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (108, 'Adriana Sinai', 'Martinez', 'Ávila', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (109, 'Edgar', 'Castillo', 'Buendia', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (110, 'Cesar Alejandro', 'Chavez', 'Gandara', 1, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (111, 'Carlos Alberto', 'Bretado', 'Juarez', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (112, 'Juan Carlos', 'Carrillo', 'Silva', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (113, 'Rafael', 'Lugo', 'Rosas', 1, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (114, 'Luis Angel', 'Rodriguez', 'Patiño', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (115, 'Sergio Adrian', 'Gandara', 'Rodriguez', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (116, 'Antonio', 'Hernandez', 'Sosa', 1, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (117, 'Cesar', 'Chavez', 'Ibarra', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (118, 'Gumaro', 'Delgado', 'Alvarado', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (119, 'Luis Antonio', 'Hernandez', 'Becerra', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (120, 'Jose', 'Estrada', 'Cervantes', 1, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (121, 'Jose', 'Rueda', 'Segura', 1, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (122, 'Genaro', 'Parra', 'Perez', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (123, 'Oscar Isidro', 'Chavez', 'Mata', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (124, 'Jesus', 'Ballato', 'Santos', 1, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (125, 'Jose Manuel', 'Duran', 'Lozano', 2, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (126, 'Julio', 'Delgado', 'Alvarado', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (127, 'Rene', 'Delgado', 'Alvarado', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (128, 'Luis Enrique', 'Luna', 'Sida', 1, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (129, 'Eduardo', 'Soto', 'Galvan', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (130, 'Jose Luis', 'Chavez', 'Mata', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (131, 'Ruben Meregildo', 'Navarez', 'Gonzalez', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (132, 'Blas', 'Avila', 'Garcia', 1, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (133, 'Jorge Isidro', 'Avila', 'Moreno', 1, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (134, 'Sergio', 'Castañeda', 'Ramirez', 1, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (135, 'Leonor Ignacio', 'Chavez', 'Montoya', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (136, 'Francisco', 'Rodriguez', 'Serrano', 1, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (137, 'Jose Antonio', 'Rodriguez', 'Serrano', 1, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (138, 'Cody Rudy', 'Primero', 'Corral', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (139, 'Jose Alberto', 'Estrada', 'Reyes', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (140, 'Jesus Manuel', 'Nuñez', 'Moncivais', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (141, 'Jesus Rene', 'Ortega', 'Chavarria', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (142, 'Virgilio', 'Fuentes', 'Ortega', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (143, 'Jaime Rene', 'Montes', 'Zamarron', 1, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (144, 'Carlos', 'Vazquez', 'Sanchez', 1, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (145, 'Raúl', 'Constantino', 'Martínez', 1, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (146, 'Pascual de Jesús', 'Orozco', 'Lázaro', 1, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (147, 'Jose Guadalupe', 'Uicab', 'Mejía', 1, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (148, 'Daniel', 'Juarez', 'Perez', 1, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (149, 'Evelin Anel', 'Blanco', 'Cárdenas', 1, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (150, 'Moises', 'Kinil', 'Mex', 1, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (151, 'Alex Emilio', 'Ic ', 'Caamal', 1, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (152, 'Oscar de Jesus ', 'Perez ', 'Martinez', 1, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (153, 'Melqui', 'Cruz', 'Fernandez', 0, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (154, 'Luis Ramon', 'Rosario', 'Damian', 0, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (155, 'Violeta', 'Farrah', 'Trujillo', 0, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (156, 'Oscar Iván', 'Albores', 'Zepeda', 0, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (157, 'Luis Miguel', 'Orozco', 'Clemente', 1, 0, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (158, 'Angel Ivan', 'Orozco', 'Lazaro', 0, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (159, 'Enrique', 'Chulin', 'May', 0, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (160, 'Porfirio', 'Sandoval', 'Arcos', 0, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (161, 'Sarain ', 'Gomez ', 'de la Cruz', 0, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (162, 'Fernando Josue', 'Velázquez', 'Vázquez', 0, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (163, 'Liverio', 'Hernandez', 'Hernandez', 0, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (164, 'Carla Maria', 'Ramirez', 'Garcia', 0, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (165, 'Alejandro ', 'Alvarez', 'Alatriste', 0, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (166, 'Eleazar', 'Deferia', 'Carrillo', 0, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (167, 'Jose Ediberto', 'Uh', 'Chan', 0, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (168, 'Gerardo Rene', 'Tzab', 'Cab', 0, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (169, 'Egle', 'May', 'Herrera', 0, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (170, 'Floriberto', 'García ', 'Zarate', 0, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (171, 'German ', 'Solar ', 'Lopez', 1, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (172, 'Moises Paul', 'Vazquez', 'Henestrosa', 1, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (173, 'Elizabeth', 'Martinez', 'Herrera', 1, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (174, 'Jose Alfredo', 'Gonzalez', 'Gerardo', 1, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (175, 'Donato', 'Francisco', 'Hernandez', 1, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (176, 'Antonio', 'Cruz', 'Magdalena', 1, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (177, 'Carlos ', 'Sosa', 'Cervantez', 1, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (178, 'Francisco Javier', 'Borraz', 'Jonapa', 1, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (179, 'Omar', 'Reyes', 'Escobar', 1, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (180, 'Oscar', 'Sanchez', 'Perez', 1, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (181, 'Carlos ', 'Ventura', 'Lopez Alonzo', 1, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (182, 'Judith', 'Ramirez', 'Avendaño', 0, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (183, 'Severiano', 'Chavez', 'Acosta', 0, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (184, 'Juan Daniel', 'Orozco', 'Clemente', 0, 0, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (185, 'Luciano de Jesus', 'Hernandez', 'Merchant', 0, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (186, 'Jose Adrian', 'Vazquez', 'Cruz', 0, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (187, 'Eduardo', 'Javier ', 'Ocaña', 0, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (188, 'Jose Alfredo', 'Pino', 'May', 0, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (189, 'Armando ', 'Aldana', 'Valdepeña', 0, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (190, 'Jose Francisco', 'Peralta', 'Aldana', 0, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (191, 'Praxedis', 'Sinaca', 'Colin', 0, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (192, 'Eduardo Arnulfo', 'Sinaca', 'Chagala', 0, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (193, 'Felix', 'Villanueva', 'Pineda', 0, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (194, 'Carlos Inocencio', 'Varguez', 'Escobedo', 0, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (195, 'Saul', 'Bartolon ', 'Perez', 0, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (196, 'Gelacio', 'Xocura', 'Oltehua', 0, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (197, 'Miguel Rene', 'Damian', 'Mora', 1, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (198, 'Martin', 'Moreno ', 'de la Cruz', 0, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (199, 'Leonardo', 'Alvaro', 'Sanchez', 0, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (200, 'Juan', 'Alvaro', 'Sanchez', 0, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (201, 'Erick Armin', 'Sedano', 'Garcia', 0, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (202, 'Manuel', 'Garruña', 'Perez', 0, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (203, 'Valetin', 'Canul', 'Chan', 0, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (204, 'Saul Benito', 'Diaz', 'Canul', 0, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (205, 'Jose Eligio', 'Valencia ', 'Molina', 0, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (206, 'Jorge Luis ', 'Gutierrez', 'Perez', 0, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (207, 'Edgar Ivan', 'Perez ', 'Alvarez', 1, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (208, 'Alejandra del Rosario', 'Cruz', 'Ramos', 0, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (209, 'Evanelit', 'Hernandez', 'Cortez', 0, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (210, 'Jorge Luis ', 'Sobrevilla', 'Bautista', 0, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (211, 'Enrique Alfredo', 'Chim ', 'Garrido', 0, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (212, 'Erick Jesus', 'Rodriguez', 'Aguilar', 0, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (213, 'Victor Hugo', 'Hernandez', 'Padilla', 0, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (214, 'Erendira Maria', 'Romero ', 'Berny', 0, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (215, 'Eusebio Guadalupe', 'Sanchez', 'Sanchez', 1, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (216, 'Domigo', 'Mayo', 'Díaz', 1, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (217, 'Luis Alberto', 'Borges', 'Joaquín', 0, 1, 3);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (218, 'Nora Guadalupe', 'Martinez', 'Alonso', 0, 1, 1);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (219, 'Juan Carlos', 'Cuevas', 'Cerón', 0, 1, 1);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (220, 'Sergio', 'Rojas', 'Cruz', 0, 1, 1);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (222, 'Hector Gibran', 'Ochoa', 'Alvarez', 1, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (223, 'Carolina', 'Luna ', 'Perez', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (224, 'Jose Cerari', 'Diaz ', 'Perez', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (225, 'Misael ', 'Paredes', 'Bojorquez', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (226, 'Paul ', 'Saenz', 'Rodriguez', 0, 1, 2);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (227, 'Gerardo ', 'Gómez', 'Ramos', 0, 1, 1);
INSERT INTO BRIGADA_Brigadistas (BrigadistaID, Nombre, ApellidoPaterno, ApellidoMaterno, PuestoID, Activo, EmpresaID) VALUES (228, 'Camilo Eladio', 'Montecinos', 'Arce', 0, 1, 1);

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
